# Generated by Django 4.0.4 on 2022-05-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('is_edit', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=32, null=True, verbose_name='Результат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='user',
        ),
        migrations.DeleteModel(
            name='MainModel',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
